[project]
name = "y2b"
version = "0.1.0"
description = "Script for reposting YouTube videos to Bilibili"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
	"openai",
	"python-dotenv",
	"pyyaml"
]

